version: '3'

tasks:
  test:
    cmds:
      - cargo test
  build:
    cmds:
      - cargo build
  run:
    cmds:
      - cargo run
  ci:
    deps: [test, build]
    silent: true
  commit:
    cmds:
      - git add * .lishrc
      - git status
      - echo "Write commit message:"
      - "read && git commit -m \"$REPLY\""
      - git push

