version: '3'

tasks:
  test:
    cmds:
      - reset
      - pytest test
  linter:
    cmds:
      - flake8 . --ignore=E501 --count
  run:
    cmds:
      - reset
      - python -m LiSH
  commit:
    cmds:
      - reset
      - git add *
      - git status
      - git commit -m "Some fixes"
      - git push
