version: '3'

tasks:
  test:
    - cargo test
  build:
    - cargo build
  run:
    - winpty cargo run compose.lish
  ci:
    silent: true
    cmds:
      - cargo check
      - cargo test
  commit:
    - git push
    - git add * .lishrc .gitignore .github
    - git status
    - "echo \"Write commit message:\" && read && git commit -m \"$REPLY\""
    - git push
