version: '3'

tasks:
  test:
    cmds:
      - cargo test
  build:
    cmds:
      - cargo build
  run:
    cmds:
      - cargo run compose.lish
  ci:
    deps: [test]
    silent: true
    cmds:
      - cargo check
  commit:
    cmds:
      - git add * .lishrc
      - git restore --staged history.txt
      - git status
      - "echo \"Write commit message:\" && read && git commit -m \"$REPLY\""
      - git push

