version: '3'

tasks:
  test:
    cmds:
      - cargo test
  build:
    cmds:
      - cargo build
  run:
    cmds:
      - winpty cargo run compose.lish
  ci:
    silent: true
    cmds:
      - cargo check
      - cargo test
  commit:
    cmds:
      - git push
      - git add * .lishrc .gitignore .github
      - git status
      - "echo \"Write commit message:\" && read && git commit -m \"$REPLY\""
      - git push

